# Generated by Django 5.0.7 on 2024-08-08 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('get_class', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('f_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 8, 23, 14, 7, 759432))),
                ('updated_at', models.DateTimeField(null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Student Information',
                'db_table': 'student_info',
            },
        ),
    ]
